namespace MtApi
{
    public enum EnumChartPropertyInteger
    {
        CHART_BRING_TO_TOP          = 35,
        CHART_MOUSE_SCROLL          = 42,
        CHART_EVENT_MOUSE_MOVE      = 40,
        CHART_EVENT_OBJECT_CREATE   = 38,
        CHART_EVENT_OBJECT_DELETE   = 39,
        CHART_MODE                  = 0,
        CHART_FOREGROUND            = 1,
        CHART_SHIFT                 = 2,
        CHART_AUTOSCROLL            = 4,
        CHART_QUICK_NAVIGATION      = 45,
        CHART_SCALE                 = 5,
        CHART_SCALEFIX              = 6,
        CHART_SCALEFIX_11           = 7,
        CHART_SCALE_PT_PER_BAR      = 10,
        CHART_SHOW_OHLC             = 12,
        CHART_SHOW_BID_LINE         = 13,
        CHART_SHOW_ASK_LINE         = 14,
        CHART_SHOW_LAST_LINE        = 15,
        CHART_SHOW_PERIOD_SEP       = 16,
        CHART_SHOW_GRID             = 17,
        CHART_SHOW_VOLUMES          = 18,
        CHART_SHOW_OBJECT_DESCR     = 19,
        CHART_VISIBLE_BARS          = 100,
        CHART_WINDOWS_TOTAL         = 101,
        CHART_WINDOW_IS_VISIBLE     = 102,
        CHART_WINDOW_HANDLE         = 103,
        CHART_WINDOW_YDISTANCE      = 110,
        CHART_FIRST_VISIBLE_BAR     = 104,
        CHART_WIDTH_IN_BARS         = 105,
        CHART_WIDTH_IN_PIXELS       = 106,
        CHART_HEIGHT_IN_PIXELS      = 107,
        CHART_COLOR_BACKGROUND      = 21,
        CHART_COLOR_FOREGROUND      = 22,
        CHART_COLOR_GRID            = 23,
        CHART_COLOR_VOLUME          = 24,
        CHART_COLOR_CHART_UP        = 25,
        CHART_COLOR_CHART_DOWN      = 26,
        CHART_COLOR_CHART_LINE      = 27,
        CHART_COLOR_CANDLE_BULL     = 28,
        CHART_COLOR_CANDLE_BEAR     = 29,
        CHART_COLOR_BID             = 30,
        CHART_COLOR_ASK             = 31,
        CHART_COLOR_LAST            = 32,
        CHART_COLOR_STOP_LEVEL      = 33,
        CHART_SHOW_TRADE_LEVELS     = 34,
        CHART_DRAG_TRADE_LEVELS     = 43,
        CHART_SHOW_DATE_SCALE       = 36,
        CHART_SHOW_PRICE_SCALE      = 37,
        CHART_IS_OFFLINE            = 112
    }
}
