namespace MtApi
{
    public enum EnumObjectPropertyInteger
    {
        OBJPROP_COLOR           = 6,
        OBJPROP_STYLE           = 7,
        OBJPROP_WIDTH           = 8,
        OBJPROP_BACK            = 9,
        OBJPROP_ZORDER          = 207,
        OBJPROP_HIDDEN          = 208,
        OBJPROP_SELECTED        = 17,
        OBJPROP_READONLY        = 1028,
        OBJPROP_TYPE            = 18,
        OBJPROP_TIME            = 19,
        OBJPROP_SELECTABLE      = 1000,
        OBJPROP_CREATETIME      = 998,
        OBJPROP_LEVELS          = 200,
        OBJPROP_LEVELCOLOR      = 201,
        OBJPROP_LEVELSTYLE      = 202,
        OBJPROP_LEVELWIDTH      = 203,
        OBJPROP_ALIGN           = 1036,
        OBJPROP_FONTSIZE        = 100,
        OBJPROP_RAY_RIGHT       = 1004,
        OBJPROP_ELLIPSE         = 11,
        OBJPROP_ARROWCODE       = 14,
        OBJPROP_TIMEFRAMES      = 15,
        OBJPROP_ANCHOR          = 1011,
        OBJPROP_XDISTANCE       = 102,
        OBJPROP_YDISTANCE       = 103,
        OBJPROP_STATE           = 1018,
        OBJPROP_XSIZE           = 1019,
        OBJPROP_YSIZE           = 1020,
        OBJPROP_XOFFSET         = 1033,
        OBJPROP_YOFFSET         = 1034,
        OBJPROP_BGCOLOR         = 1025,
        OBJPROP_CORNER          = 101,
        OBJPROP_BORDER_TYPE     = 1029,
        OBJPROP_BORDER_COLOR    = 1035
    }
}
